### ISSUE TITLE
Comparison with conventional lateral MSD curves for planar membranes

### ISSUE THREAD

**Issue by p-j-smith** [balazsfabian/curved-diffusion#1]
Hi,

This seems like a very cool approach to calculating diffusion on curved membranes! I worked a little bit on calculating diffusion in buckled bilayers but I ran into a few issues.

I'm wondering whether you have compared this approach to the conventional lateral MSD on a planar bilayer? I saw in the SI that you calculated the MSD of planar bilayers using the conventional MSD, but I couldn't see the values of D calculated using the geodesic MSD. I think this would be a nice way to verify this approach. Sorry I have just missed these values.

And thank you for making this freely available and open-source, I'll definitely be trying out the command line tool!

**Comment by balazsfabian** [comment]
Hi,

I'm glad to hear you like it!

If you create a fine enough mesh, then the 2-dimensional (xy-projected) D values with this tool and conventional approaches match up nicely. 

Please not, that the code is an early stage, but definitely usable. The parallel parts withs calls to the external VTP surely need more work. Suggestions / bug reports / pull requests are appreciated. Let me know how it goes, and what you think about it!

**Comment by p-j-smith** [comment]
I see, that makes sense, thanks for the explanation. And thanks for the warning about it being in an early stage...I'll let you know if I stumble into any issues!
